---
- name: setup pcf operator environment
  hosts: all
  vars_files:
    - vars.yml
  become: true

  pre_tasks:
    - name: upgrade apt repositories
      apt:
        update_cache: true

  roles:
    - lastpass
    - docker-ce
    - python
    - misc
    - pcf

  post_tasks:
    - name: cleanup apt packages
      apt:
        autoclean: true
        autoremove: true

- name: setup vagrant user
  hosts: pcf-vagrant-client
  vars:
    user: vagrant
  become: true

  roles:
    - lastpass-user
    - docker-user
    - vim
    - tmux