---
- name: install vim
  apt:
    name: vim

- name: creates vim directory
  become_user: "{{user}}"
  file: 
    path: /home/{{user}}/.vim
    state: directory

- name: install vundle package manager
  become_user: "{{user}}"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/{{user}}/.vim/bundle/Vundle.vim

- name: setup vim
  become_user: "{{user}}"
  copy:
    src: tasks/vim/.vimrc
    dest: /home/{{user}}/
